apiVersion: apps/v1
kind: Deployment
metadata:
  name: krishna-deploy
  labels:
    app: krishna-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: krishna-app
  template:
    metadata:
      labels:
        app: krishna-app
    spec:
      containers:
      - name: krishna-container
        image: bvky/sa-webappsimage:v2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: krishna-service
  labels:
    app: krishna-app
spec:
  selector:
    app: krishna-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31029
    port: 8080
    targetPort: 8080
